### ISSUE TITLE
readme - minor type

### ISSUE THREAD

**Issue by damien1** [Theys96/hugo-fuse-search#5]
Great too see what you have done here ... and I'm trying to get it going now

For config.toml .. there is a typo

Activate search in your config.toml or config.yaml (example in toml):

```
[outputs]
home = ["HTML", "RSS", "JSON"]

[params.search]
enabled = true
keyboardControlled: topSearchbar

[params.search.topSearchbar]
enabled = true
```

should be ...
`keyboardControlled = "topSearchbar"`

**Comment by Theys96** [comment]
Thanks for catching that!
